name: lipseek
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.12
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - torchmetrics
  - onnxruntime
  - opencv
  - pillow
  - tqdm
  - optuna
  - wandb
  - datasets
  - ipykernel
  - pyparsing
  - flask
  - flask-cors

# Make sure to install your machines proper pytorch with cuda, for instance: 
# conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
